(()=>{'use strict';
const storageKey='ase-course-v1';let state={completed:{},answers:{}};let persistOK=true;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&typeof saved==='object')state={completed:saved.completed&&typeof saved.completed==='object'?saved.completed:{},answers:saved.answers&&typeof saved.answers==='object'?saved.answers:{},results:saved.results||{},labResults:saved.labResults||{},best:saved.best||{},edition:saved.edition||1};}catch{persistOK=false;}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));document.querySelector('#save-status').textContent='Saved in this browser.';}catch{persistOK=false;warning();}}
function warning(){if(document.querySelector('.storage-warning'))return;const p=document.createElement('p');p.className='note storage-warning';p.textContent='Browser storage is unavailable. Changes work during this visit but may not persist after leaving.';document.querySelector('.page-content').prepend(p);}
if(!persistOK)warning();
let progressData;
function update(){document.querySelectorAll('[data-reading-state]').forEach(e=>{e.textContent=state.completed[e.dataset.readingState]===true?'Reviewed':'Not reviewed';});document.querySelectorAll('[data-complete]').forEach(c=>c.checked=state.completed[c.dataset.complete]===true);if(!progressData)return;const count=progressData.keys.filter(k=>state.completed[k]===true).length,pct=Math.round(count/progressData.keys.length*100);document.querySelectorAll('[data-progress-label]').forEach(e=>e.textContent=`${pct}% complete · ${count}/${progressData.keys.length}`);document.querySelectorAll('[data-small-progress]').forEach(e=>e.textContent=pct+'%');document.querySelectorAll('[data-progress]').forEach(e=>e.value=pct);for(const w of progressData.weeks){const done=w.keys.filter(k=>state.completed[k]===true).length;document.querySelectorAll(`[data-week-percentage="${w.n}"]`).forEach(e=>e.textContent=Math.round(done/w.keys.length*100)+'% complete · '+done+'/'+w.keys.length);document.querySelectorAll(`[data-week-status="${w.n}"]`).forEach(e=>{e.textContent=done===w.keys.length?'Complete':done?Math.round(done/w.keys.length*100)+'% complete':'Not started';e.classList.toggle('complete',done===w.keys.length)});document.querySelectorAll(`[data-week-dot="${w.n}"]`).forEach(e=>{e.classList.toggle('done',done===w.keys.length);e.setAttribute('aria-label',done===w.keys.length?'Complete':'Incomplete')});}const next=progressData.activities?.find(a=>state.completed[a.key]!==true);const projectPending=progressData.keys.find(k=>(k.startsWith('p1-')||k.startsWith('p2-')||k.startsWith('project-'))&&state.completed[k]!==true);document.querySelectorAll('[data-continue]').forEach(e=>{e.href=next?next.route:projectPending?('/projects/'+(projectPending.startsWith('p1-')||projectPending.startsWith('project-1')?'1':'2')+'/'):'/progress/';e.textContent=next?`Continue · ${next.label} →`:projectPending?'Review project evidence →':'Review learning record →';});}
document.querySelectorAll('[data-complete]').forEach(c=>c.addEventListener('change',()=>{state.completed[c.dataset.complete]=c.checked;save();update();}));
document.querySelectorAll('[data-answer]').forEach(t=>{t.value=typeof state.answers[t.dataset.answer]==='string'?state.answers[t.dataset.answer]:'';t.addEventListener('input',()=>{state.answers[t.dataset.answer]=t.value;save();});});
if(!state.edition||state.edition<2){for(let w=1;w<=8;w++)delete state.completed['quiz-'+w];delete state.completed['lab-2'];state.edition=2;save();}state.results=state.results||{};state.labResults=state.labResults||{};state.best=state.best||{};window.CourseAPI={state,save,update,setComplete:(key,value)=>{state.completed[key]=value;save();update();}};window.dispatchEvent(new Event('course-ready'));update();fetch('/progress-data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{progressData=d;update()}).catch(()=>{document.querySelectorAll('[data-progress-label]').forEach(e=>e.textContent='Progress summary unavailable');});
window.addEventListener('storage',e=>{if(e.key===storageKey){try{const d=JSON.parse(e.newValue);if(d?.completed){state.completed=d.completed;update();}}catch{}}});
const menu=document.querySelector('.menu'),nav=document.querySelector('#course-nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});document.addEventListener('click',e=>{if(!nav.contains(e.target)&&!menu.contains(e.target)){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});
})();
