(()=>{'use strict';
const E=(t,cls,text)=>{const e=document.createElement(t);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const getAnswers=(root,q)=>q.kind==='order'||q.kind==='match'?[...root.querySelectorAll('select')].map(s=>s.value===''?-1:Number(s.value)):[...root.querySelectorAll('input:checked')].map(s=>Number(s.value)).sort((a,b)=>a-b);
const equal=(a,b)=>a.length===b.length&&a.every((x,i)=>x===b[i]);
function init(){const api=window.CourseAPI;if(!api){window.addEventListener('course-ready',init,{once:true});return;}
fetch('/assessments.json').then(r=>{if(!r.ok)throw Error('Assessment data unavailable');return r.json()}).then(data=>{
const questions=new Map(data.quizzes.flat().map(q=>[q.id,q]));let serial=0;
function render(root,q,key,onChecked){const controls=root.querySelector('.question-controls');const instance=++serial;const saved=api.state.results[key];const values=saved?.selected||[];
if(q.kind==='order'||q.kind==='match'){const items=q.kind==='order'?q.items:q.pairs.map(p=>p[1]);const indexes=items.map((_,i)=>i);const shuffled=indexes.slice(1).concat(indexes[0]);items.forEach((_,i)=>{const label=E('label','select-row');label.append(E('span','',q.kind==='order'?`Position ${i+1}`:q.pairs[i][0]));const select=E('select');select.setAttribute('aria-label',q.kind==='order'?`Step ${i+1}`:q.pairs[i][0]);const placeholder=E('option','', 'Choose…');placeholder.value='';select.append(placeholder);for(const k of shuffled){const o=E('option','',items[k]);o.value=k;select.append(o);}if(values[i]!==undefined&&values[i]>=0)select.value=values[i];label.append(select);controls.append(label);});}
else q.options.forEach((text,i)=>{const label=E('label','answer-option'),input=E('input');input.type=q.kind==='multi'?'checkbox':'radio';input.name='question-'+instance;input.value=i;input.checked=values.includes(i);label.append(input,E('span','',text));controls.append(label);});
function feedback(selected){const area=root.querySelector('.question-feedback');area.replaceChildren();const complete=q.kind==='order'||q.kind==='match'?selected.every(v=>v>=0):selected.length>0;if(!complete){area.append(E('p','validation-message','Choose an answer for every required field before checking.'));return null;}const correct=equal(selected,q.answer);area.append(E('p',correct?'verdict correct':'verdict incorrect',correct?'Correct. The reasoning fits this scenario.':'Review the reasoning below.'));
if(q.kind==='order'||q.kind==='match'){const ol=E('ol','rationales');q.answer.forEach((v,i)=>{const label=q.kind==='order'?q.items[v]:q.pairs[i][0]+' → '+q.pairs[v][1];ol.append(E('li','',label+'. '+q.why[i]));});area.append(ol);}else{const ul=E('ul','rationales');q.options.forEach((t,i)=>ul.append(E('li',q.answer.includes(i)?'answer-correct':'',`${q.answer.includes(i)?'Correct option':'Incorrect option'}: ${t}. ${q.feedback[i]}`)));area.append(ul);}return correct?1:0;}
root.querySelector('[data-check-answer]').addEventListener('click',()=>{const selected=getAnswers(root,q);const score=feedback(selected);if(score===null)return;api.state.results[key]={selected,score,topic:q.topic,at:Date.now()};api.save();onChecked?.();});if(saved)feedback(saved.selected);
}
function quizSummary(week){const qs=data.quizzes[week-1];const results=qs.map(q=>api.state.results[`quiz:${q.id}`]);const done=results.filter(Boolean).length,correct=results.reduce((a,r)=>a+(r?.score||0),0),score=Math.round(correct/qs.length*100);const root=document.querySelector(`[data-quiz="${week}"]`);if(root){const area=root.querySelector('.quiz-summary');area.replaceChildren(E('h3','',done===qs.length?`Score: ${score}% · ${correct}/${qs.length}`:`${done}/${qs.length} checked · ${correct} correct`));if(done<qs.length)area.append(E('p','','Check every question to complete the quiz.'));else{api.state.completed['quiz-'+week]=true;api.state.best[week]=Math.max(api.state.best[week]||0,score);api.save();api.update();area.append(E('p','',`Latest attempt: ${score}%. Best completed attempt: ${api.state.best[week]}%. You can retry after review.`));}const weak=qs.filter(q=>api.state.results[`quiz:${q.id}`]?.score===0);if(weak.length){area.append(E('h4','','Review these topics'));const ul=E('ul');for(const q of weak){const li=E('li'),a=E('a','',q.topic+' → review Week '+week);a.href=`/weeks/${week}/#lectures`;li.append(a);ul.append(li);}area.append(ul);}else if(done===qs.length)area.append(E('p','','All quiz topics passed in this attempt. Apply the same reasoning in the lab.'));}mastery();}
function mastery(){const root=document.querySelector('#mastery-overview');if(!root)return;root.replaceChildren(E('h2','','Quiz mastery'));const table=E('table');const head=E('thead');const row=E('tr');['Week','Latest score','Best score','Review'].forEach(t=>row.append(E('th','',t)));head.append(row);table.append(head);const body=E('tbody');const weak=[];data.quizzes.forEach((qs,i)=>{const rs=qs.map(q=>api.state.results[`quiz:${q.id}`]);const complete=rs.every(Boolean);const score=Math.round(rs.reduce((a,r)=>a+(r?.score||0),0)/qs.length*100);const tr=E('tr');tr.append(E('td','',String(i+1)),E('td','',complete?score+'%':rs.some(Boolean)?'In progress':'Not attempted'),E('td','',api.state.best[i+1]===undefined?'—':api.state.best[i+1]+'%'));const td=E('td'),a=E('a','','Open quiz →');a.href=`/quizzes/${i+1}/`;td.append(a);tr.append(td);body.append(tr);qs.forEach(q=>{if(api.state.results[`quiz:${q.id}`]?.score===0)weak.push({topic:q.topic,week:i+1});});});table.append(body);const wrap=E('div','table-wrap');wrap.append(table);root.append(wrap);root.append(E('h3','','Recommended review'));if(!weak.length)root.append(E('p','','No weak topics recorded yet. Complete the quizzes to build a review map.'));else{const ul=E('ul');for(const x of weak){const li=E('li'),a=E('a','',x.topic+` · Week ${x.week}`);a.href=`/weeks/${x.week}/#lectures`;li.append(a);ul.append(li);}root.append(ul);}}
document.querySelectorAll('[data-question]').forEach(root=>{const q=questions.get(root.dataset.question);if(!q)return;const context=root.dataset.context||'quiz';render(root,q,context+':'+q.id,()=>{if(context==='quiz')quizSummary(Number(q.id[0]));});});
document.querySelectorAll('[data-quiz]').forEach(r=>quizSummary(Number(r.dataset.quiz)));document.querySelectorAll('[data-retry-quiz]').forEach(b=>b.addEventListener('click',()=>{const week=Number(b.dataset.retryQuiz);data.quizzes[week-1].forEach(q=>delete api.state.results['quiz:'+q.id]);api.state.completed['quiz-'+week]=false;api.save();location.reload();}));
for(const root of document.querySelectorAll('[data-lab-exercise]')){const id=root.dataset.labExercise,e=data.labs[id];if(!e)continue;
if(e.kind==='retrieval'){root.append(E('p','fixture-label','ILLUSTRATIVE FIXTURE · 100 QUESTIONS · NOT A LIVE BENCHMARK'));const wrap=E('div','table-wrap'),table=E('table');table.innerHTML='<thead><tr><th>Architecture</th><th>Recall</th><th>Correct</th><th>Citation precision</th><th>p95</th><th>Tokens/query</th><th>Index</th></tr></thead><tbody><tr><td>A · Vector</td><td>88%</td><td>87%</td><td>92%</td><td>1.2s</td><td>2,100</td><td>Dense chunks</td></tr><tr><td>B · Hybrid</td><td>96%</td><td>93%</td><td>98%</td><td>1.8s</td><td>2,600</td><td>Lexical + dense</td></tr><tr><td>C · Document navigation</td><td>95%</td><td>94%</td><td>98%</td><td>3.4s</td><td>4,800</td><td>Catalog + tree</td></tr><tr><td>D · Long context</td><td>100%</td><td>91%</td><td>96%</td><td>5.1s</td><td>18,000</td><td>No retrieval index</td></tr></tbody>';wrap.append(table);root.append(wrap);const q={id:'lab2',kind:'single',type:'Constraint diagnosis',topic:'RAG architecture',prompt:e.task,options:['A · Vector','B · Hybrid','C · Document navigation','D · Long context'],answer:[1],feedback:['Fails correctness and citation requirements.','Meets all hard constraints; compare cost/maintenance among feasible candidates.','Good quality but exceeds the p95 limit.','Context contains evidence but exceeds latency and does not guarantee perfect answers.']};const box=makeBox(q);root.append(box);render(box,q,'lab:2',()=>{api.state.labResults[id]=api.state.results['lab:2'];api.save();});}
else{const q={id:'lab'+id,kind:e.single?'single':'multi',type:e.kind==='architecture'?'Architecture design':'Production debugging',topic:e.title,prompt:e.task,options:e.options,answer:e.answer,feedback:e.feedback};const box=makeBox(q);root.append(box);render(box,q,'lab:'+id,()=>{api.state.labResults[id]=api.state.results['lab:'+id];api.save();});}}
function makeBox(q){const box=E('div','assessment');box.append(E('h3','',q.prompt),E('div','question-controls'));const button=E('button','button primary','Validate design / diagnosis');button.dataset.checkAnswer='';const feedback=E('div','question-feedback');feedback.setAttribute('aria-live','polite');box.append(button,feedback);return box;}
mastery();
}).catch(()=>{document.querySelectorAll('.quiz-workspace,.lab-exercise').forEach(e=>e.prepend(E('p','note','Interactive questions could not load. Reload the page; the written lesson and lab instructions remain available.')));});
}
init();
})();
