(()=>{'use strict';
const api=window.CourseAPI;if(!api)return;
const answers=()=>api.state.answers;
function updateJourney(){
 document.querySelectorAll('[data-unit-state]').forEach(e=>{const id=e.dataset.unitState;const done=api.state.completed['unit-v3-'+id];const draft=answers()['v3-practice-'+id];e.textContent=done?'Reviewed ✓':draft?'In progress →':'Start →';});
 for(let w=1;w<=8;w++){const values=Array.from({length:8},(_,i)=>answers()['v3-rating-'+w+'-'+i]);const reviewed=values.filter(v=>['0','1','2','3'].includes(v));const score=reviewed.reduce((s,v)=>s+Number(v),0);document.querySelectorAll(`[data-review-summary="${w}"]`).forEach(e=>{e.textContent=`Independent review: ${reviewed.length}/8 rated · ${score}/24 points (self / recorded reviewer). ${reviewed.length===8?(score>=18?'Suggested readiness threshold reached; check unresolved security/evidence errors.':'Revisit weak units before the project defense.'):'Complete all eight responses and rubric reviews.'}`;});api.state.completed['review-v3-'+w]=reviewed.length===8;}
}
function changed(){updateJourney();api.save();api.update();}
for(const el of document.querySelectorAll('[data-route-choice]')){const key='v3-route-'+el.dataset.routeChoice;el.value=answers()[key]||'';el.addEventListener('change',()=>{answers()[key]=el.value;changed();});}
for(const el of document.querySelectorAll('[data-review-rating]')){const key='v3-rating-'+el.dataset.reviewRating;el.value=answers()[key]??'';el.addEventListener('change',()=>{answers()[key]=el.value;changed();});}
document.querySelectorAll('[data-answer]').forEach(e=>e.addEventListener('input',updateJourney));
document.querySelectorAll('[data-complete]').forEach(e=>e.addEventListener('change',updateJourney));
document.querySelectorAll('[data-clear-review]').forEach(b=>b.addEventListener('click',()=>{const w=b.dataset.clearReview;for(let i=0;i<8;i++)delete answers()['v3-rating-'+w+'-'+i];document.querySelectorAll(`[data-review-rating^="${w}-"]`).forEach(e=>e.value='');changed();}));
document.querySelectorAll('[data-load-video]').forEach(b=>b.addEventListener('click',()=>{const box=b.closest('[data-video]'),id=box.dataset.video;if(!/^[a-zA-Z0-9_-]{11}$/.test(id))return;const frame=document.createElement('iframe');frame.src='https://www.youtube-nocookie.com/embed/'+id+'?cc_load_policy=1';frame.title='Assigned course recording';frame.allow='accelerometer; encrypted-media; gyroscope; picture-in-picture; fullscreen';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';box.replaceChildren(frame);}));
const finiteValues=form=>Object.fromEntries(Array.from(form.querySelectorAll('input')).map(x=>[x.name,Number(x.value)]));
function calculate(form){const v=finiteValues(form),out=form.querySelector('output');if(!form.checkValidity()||Object.values(v).some(x=>!Number.isFinite(x)||x<0)){out.textContent='Enter valid non-negative values in every field.';return;}const mode=form.dataset.sim;if(mode==='context'){const used=v.output+v.policy+v.task+v.memory,remaining=v.window-used;out.textContent=remaining<0?`Over budget by ${(-remaining).toLocaleString()} tokens. Reduce reserved inputs before generation.`:`${remaining.toLocaleString()} tokens available for evidence (${(remaining/v.window*100).toFixed(1)}% of window).`;const strip=form.querySelector('.budget-strip');strip.replaceChildren();for(const[name,value]of [['Output',v.output],['Policy/tools',v.policy],['Task',v.task],['Memory',v.memory],['Evidence',Math.max(0,remaining)]]){const s=document.createElement('span');s.style.flexGrow=String(value);s.textContent=name+' '+value.toLocaleString();s.title=s.textContent;strip.append(s);}}
if(mode==='kv'){const bytes=2*v.layers*v.heads*v.dim*v.bytes*v.tokens;out.textContent=`${(bytes/2**20).toLocaleString(undefined,{maximumFractionDigits:2})} MiB per sequence · ${(bytes*v.sequences/2**30).toLocaleString(undefined,{maximumFractionDigits:2})} GiB across ${v.sequences} active sequences.`;}
if(mode==='rrf'){const a=1/(v.k+v.a1)+1/(v.k+v.a2),b=1/(v.k+v.b1)+1/(v.k+v.b2);out.textContent=`A: ${a.toFixed(6)} · B: ${b.toFixed(6)} · ${Math.abs(a-b)<1e-12?'Tie':a>b?'A ranks first':'B ranks first'}. Rank fusion does not establish evidence support.`;}}
document.querySelectorAll('[data-sim]').forEach(f=>{f.addEventListener('submit',e=>{e.preventDefault();calculate(f);});calculate(f);});
const loopSteps=[['State','Goal: compare P1 and P2. One evidence item is missing. Budget: 3 tool calls.'],['Proposal','The model proposes fetch_section(P2, results). This is an untrusted typed action request.'],['Policy','Runtime validates schema, source scope, deadline and remaining budget. A denied call would stop here.'],['Observation','The permitted tool returns a contradictory result with source revision and span. Budget becomes 2.'],['Finish / replan','Update the evidence ledger. Return a qualified comparison or request one bounded follow-up; never erase the contradiction.']];
document.querySelectorAll('[data-loop]').forEach(box=>{let i=0;const prev=box.querySelector('[data-loop-prev]'),next=box.querySelector('[data-loop-next]');function render(){box.querySelector('[data-loop-detail]').textContent=`${i+1}/5 · ${loopSteps[i][0]}: ${loopSteps[i][1]}`;box.querySelectorAll('.loop-states span').forEach((e,j)=>e.classList.toggle('active',i===j));prev.disabled=i===0;next.disabled=i===4;}prev.addEventListener('click',()=>{i=Math.max(0,i-1);render();});next.addEventListener('click',()=>{i=Math.min(4,i+1);render();});render();});
function transferStatus(text){const e=document.querySelector('[data-transfer-status]');if(e)e.textContent=text;}
document.querySelector('[data-export-progress]')?.addEventListener('click',()=>{const payload={format:'ase-learning-record',formatVersion:1,exportedAt:new Date().toISOString(),state:api.state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ase-learning-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);transferStatus('Learning record exported. It includes your local drafts and evidence notes.');});
function validateImport(text){const data=JSON.parse(text,(k,v)=>{if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe record key');return v;});if(data.format!=='ase-learning-record'||data.formatVersion!==1||!data.state||typeof data.state!=='object')throw Error('Choose an A/SE learning-record export.');const s=data.state;if(!s.completed||Array.isArray(s.completed)||typeof s.completed!=='object'||!s.answers||Array.isArray(s.answers)||typeof s.answers!=='object')throw Error('The record is missing completion or answer data.');if(Object.values(s.completed).some(x=>typeof x!=='boolean')||Object.values(s.answers).some(x=>typeof x!=='string'))throw Error('The record contains invalid completion or answer values.');return s;}
window.CourseJourney={validateImport,calculate,updateJourney};
document.querySelector('[data-import-progress]')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('Record exceeds the 2 MB import limit.');const s=validateImport(await file.text());if(!window.confirm('Replace this browser’s learning record with the selected export? Export the current record first if you need a backup.'))return;for(const key of ['completed','answers','results','labResults','best'])api.state[key]=s[key]||{};api.state.edition=3;api.save();location.reload();}catch(error){transferStatus('Import not applied: '+error.message);}finally{e.target.value='';}});
updateJourney();api.update();
})();
