services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.107.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports: ["4317:4317", "4318:4318"]
    depends_on: [tempo, prometheus, loki]
  tempo:
    image: grafana/tempo:2.6.1
    command: ["-config.file=/etc/tempo.yaml"]
    volumes: ["./tempo.yaml:/etc/tempo.yaml:ro", "tempo-data:/var/tempo"]
    ports: ["3200:3200"]
  prometheus:
    image: prom/prometheus:v2.54.1
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml:ro", "prometheus-data:/prometheus"]
    ports: ["9090:9090"]
  loki:
    image: grafana/loki:3.2.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes: ["./loki.yaml:/etc/loki/local-config.yaml:ro", "loki-data:/loki"]
    ports: ["3100:3100"]
  grafana:
    image: grafana/grafana:11.2.2
    depends_on: [tempo, prometheus, loki]
    volumes:
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/ase-dashboard.json:ro
      - ./dashboards-provisioning.yaml:/etc/grafana/provisioning/dashboards/custom.yaml:ro
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - grafana-data:/var/lib/grafana
    ports: ["3000:3000"]
volumes:
  tempo-data:
  prometheus-data:
  loki-data:
  grafana-data:
