"""Deterministic Week 7 grader; recomputes evidence from raw workflow rows."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REQUIRED=['trace completeness','latency p50/p95','error rate','retry rate','tokens/request','cost/request']; MIN=20
def read():
 m=json.loads((ROOT/'data/manifest.json').read_text()) if (ROOT/'data/manifest.json').exists() else {}; x=json.loads((ROOT/'reports/metrics.json').read_text()) if (ROOT/'reports/metrics.json').exists() else {}; rs=[json.loads(x) for x in (ROOT/'reports/results.jsonl').read_text().splitlines()] if (ROOT/'reports/results.jsonl').exists() else []; return m,x,rs
def ev(ok,obs,req,msg): return {'passed':bool(ok),'observed':obs,'required':req,'message':msg}
def checks():
 m,x,rs=read(); vals=x.get('required_metrics',{}); unique=len({r.get('run_id') for r in rs})==len(rs) and bool(rs); shape=all(r.get('trace_id') and len(r.get('spans',[]))>=5 and r.get('journal') for r in rs); telemetry=(ROOT/'reports/telemetry.ndjson').exists(); expected=sum(1 for r in rs if r.get('retry_count',0)>0); recorded=sum(1 for r in rs if any(e.get('event')=='retry_scheduled' for e in r.get('journal',[]))); imported=m.get('upstream_week')==4; provenance=all(r.get('source',{}).get('mode')=='imported_week4_planner_executor' and r.get('source',{}).get('source_id') and r.get('source',{}).get('live_execution') is True and r.get('source',{}).get('live_runtime',{}).get('runtime',{}).get('live_execution') is True and r.get('request_id')==r.get('run_id') for r in rs) if imported else True; source_spans=all({'planner.execute','executor.execute','verifier.check'}.issubset({s.get('name') for s in r.get('spans',[])}) for r in rs) if imported else True; measured=all(r.get('timing_mode')=='measured_wall_clock' and all(isinstance(s.get('duration_ms'),(int,float)) and s.get('duration_ms')>=0 for s in r.get('spans',[])) for r in rs)
 return {'metrics_file':ev(bool(x),'present' if x else 'missing','reports/metrics.json','run make run'),'real_data':ev(m.get('status')=='real_data',m.get('status','missing'),'real_data','run the pinned fetch command'),'minimum_cases':ev(m.get('cases',0)>=MIN,m.get('cases',0),f'>= {MIN}','meet the run count'),'raw_results':ev(unique,len(rs),'unique run rows','preserve raw state'),'durable_shape':ev(shape,'journals, spans and statuses' if shape else 'missing durable evidence','journal + 5 spans per run','run the workflow'),'required_metrics':ev(set(vals)==set(REQUIRED),sorted(vals),REQUIRED,'write all observability metrics'),'numeric_metrics':ev(all(isinstance(v,(int,float)) or isinstance(v,list) for v in vals.values()),vals,'numeric values','recompute from raw rows'),'retry_evidence':ev(expected==recorded,{'expected':expected,'recorded':recorded},'same retry denominator','record retry events'),'telemetry_export':ev(telemetry,'reports/telemetry.ndjson','local telemetry audit copy','emit OTLP or local telemetry'),'provenance':ev(provenance,'Week 4 request IDs and source artifacts' if provenance else 'missing source provenance','preserve imported request IDs','run with --from-week4'),'source_runtime_spans':ev(source_spans,'planner, executor and verifier spans' if source_spans else 'missing Week 4 runtime spans','three source runtime spans per imported run','instrument imported runtime'),'measured_timing':ev(measured,'measured wall-clock span durations' if measured else 'fabricated or missing span timing','measured non-negative duration_ms','record span start/end'),'artifact':ev((ROOT/'reports/observability_report.md').exists() and (ROOT/'reports/observability_report.md').stat().st_size>300,'reports/observability_report.md','measured report','write the report')}
def grade():
 c=checks(); bad=[f'{k}: {v["message"]}' for k,v in c.items() if not v['passed']]; result={'status':'pass' if not bad else 'fail','summary':{'passed':sum(v['passed'] for v in c.values()),'total':len(c)},'checks':c,'errors':bad}; (ROOT/'reports/grade.json').write_text(json.dumps(result,indent=2)+'\n'); print(('GRADE PASS' if not bad else 'GRADE FAIL')+'\n'+json.dumps(result,indent=2)); raise SystemExit(1 if bad else 0)
def step(n):
 m,x,rs=read(); vals=x.get('required_metrics',{}); c=checks(); tests={1:bool(x and x.get('cases',0)>0),2:bool(x.get('methods')==['retrieval','model','tool','verification','approval']),3:bool(rs and all(len(r.get('spans',[]))>=5 for r in rs)),4:m.get('status')=='real_data',5:m.get('cases',0)>=MIN,6:x.get('cases')==len(rs) and len(rs)>=MIN,7:set(vals)==set(REQUIRED),8:all(isinstance(v,(int,float)) or isinstance(v,list) for v in vals.values()),9:len({r.get('run_id') for r in rs})==len(rs),10:c['provenance']['passed'] and c['source_runtime_spans']['passed'],11:c['telemetry_export']['passed'] and c['measured_timing']['passed'],12:c['artifact']['passed']}; ok=tests.get(n,False); print(f'STEP {"PASS" if ok else "FAIL"} {n}: observed {tests.get(n)}'); raise SystemExit(0 if ok else 1)
if __name__=='__main__':
 p=argparse.ArgumentParser(); p.add_argument('command'); a=p.parse_args(); grade() if a.command=='grade' else step(int(a.command.rsplit('-',1)[1])) if a.command.startswith('check-step-') else print('use grade or check-step-N')
